### PR TITLE
fixed npm bundling issue

### PR DESCRIPTION
**Pull request by iangilman**
With version 0.4.0 I added util.ts, but didn't think to add it to the bundling code. I've now fixed that with this patch (already published to npm as 0.4.1 so I could test it). It seems to work, but I'm guessing it could be more elegant… Any suggestions, @Dan503?

### CODE REVIEW

**Comment by Dan503** [comment]
Is there any time when you imagine yourself importing utils without also importing Driftory?

If not, I would discard these changes and export the utils from driftory.ts.

```js
// driftory.ts
import x from 'x'
import y from 'y'
import z from 'z'

export * from './util'

// The rest of driftory.ts
```

I want to be able to import all my stuff from a single line

```js
import Driftory, { mapLinear } from 'driftory'
```

**Comment by Dan503** [comment]
The method you have used in this PR will require people to do this:

```js
import Driftory from 'driftory'
import { mapLinear } from 'driftory/dist/utils'
```

**Comment by iangilman** [comment]
The util file is used only by Driftory… There's no need for anyone (besides Driftory) to import it, so there's no need for Driftory to export it. You could think of it as a dependency that Driftory has that's bundled with Driftory.

I originally published it without doing the bundling, but on the other hand, my build tool balked at the fact that Driftory imported it even though it wasn't present. So now with this change it is present in the distribution, but only for Driftory to import.

The thing I'm curious about is whether there's a better way to do the bundling (or even build the util directly into Driftory) with gulp.

Obviously neither approach is to copy the functions from the util file into the Driftory file, but I figured if I could keep them separate it would feel just a little cleaner.

**Comment by Dan503** [comment]
Ahh ok, I didn't understand what the objective you were trying to achieve was.

I'll take another look. There is definitely a cleaner way to do what you are trying to do.

**Review by Dan503 — APPROVED** [review]
I made the following change to how the npm-pakage is generated:
https://github.com/pixfabrik/driftory-viewer/pull/38/commits/025068d271568cecbed52667694746586edf65d9

**Comment by iangilman** [comment]
Beautiful… Thank you! I'm still learning how gulp works :-)

**Pull request merged**
