### PR TITLE
Cleaned up version of PR #6

### PR DESCRIPTION
**Pull request by iangilman**
@Dan503 good point about the Prettier changes… Easy enough to fix.

Of course it wouldn't have been an issue at all if you had run Prettier on your patch in the first place ;-)

Anyway, here you go… The description from https://github.com/pixfabrik/driftory-viewer/pull/6 apply. Thank you for taking a look!

### CODE REVIEW

**Comment by Dan503** [comment]
Sorry, my Prettier is malfunctioning on this project for some reason. I cant' get it to format on save.

Me closing the other PR was also a bit of a rushed move. I forgot that fixing the prettier issues on MAster branch would fix the difficult-to-review issue.

I ended up doing the prettier change myself in the CLI on master branch to clean up the PR differences.

@iangilman can you take a look at the changes I've made before merging?

**Review by Dan503 — APPROVED** [review]
I've made changes to fix issues in the PR. Please review before merging.

**Review by iangilman — COMMENTED** [review]
Looks great! Thank you for cleaning things up with me :-)

**Comment by Dan503** [comment]
@iangilman don't forget to publish if you haven't already.

Did you end up giving me publish permission on npm for the @driftory project?

**Comment by iangilman** [comment]
Whoops, thanks for the reminder! I have now published.

Looks like I haven't set you up with publish permission on that project yet. I think for now let's see if I remember to publish as needed…

**Pull request merged**
